// <auto-generated />
using Car_House.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Car_House.Migrations
{
    [DbContext(typeof(CarDbContext))]
    partial class CarDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9");

            modelBuilder.Entity("Car_House.Models.Car", b =>
                {
                    b.Property<int>("CarID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BodyType")
                        .HasColumnType("TEXT");

                    b.Property<int>("BrandID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CarDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Condition")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayImage")
                        .HasColumnType("TEXT");

                    b.Property<int>("EngineType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FuelType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GearType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Images")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Mileage")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NoOfSeats")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("SteeringType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Transmission")
                        .HasColumnType("INTEGER");

                    b.HasKey("CarID");

                    b.ToTable("CarList");

                    b.HasData(
                        new
                        {
                            CarID = 1,
                            BodyType = "d",
                            BrandID = 0,
                            BrandName = "Audi",
                            CarDescription = "this is Audi",
                            Category = 0,
                            Color = "black",
                            Condition = 0,
                            EngineType = 1,
                            FuelType = 1,
                            GearType = 0,
                            Mileage = 50m,
                            Model = "Audi a1 ambition",
                            NoOfSeats = 5,
                            Price = 5000000m,
                            SteeringType = 0,
                            Transmission = 0
                        },
                        new
                        {
                            CarID = 2,
                            BodyType = "d",
                            BrandID = 0,
                            BrandName = "BMW",
                            CarDescription = "this is BMW",
                            Category = 2,
                            Color = "silver",
                            Condition = 0,
                            EngineType = 1,
                            FuelType = 1,
                            GearType = 0,
                            Mileage = 50m,
                            Model = "BMW-1",
                            NoOfSeats = 5,
                            Price = 7000000m,
                            SteeringType = 0,
                            Transmission = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
